# Visit the Docker compose reference guide for more information
# https://docs.docker.com/compose/compose-file/

# develop micro services
version: '0.2'
services:
      
  # create producer service
  producer:
    # configure build properties
    build: 
      # set build context to producer devcontainer
      context: ./.devcontainer/producer
      # limit build to development stage
      target: development
    # bind host to container to persist file changes
    volumes:
      - .:/workspace:cached
    # add service dependencies
    depends_on:
      - consumer
    # add service to network
    networks:
      - PingPong
    # enable allocation of terminal to container
    tty: true
    # keep standard input open on container
    stdin_open: true
    # overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  
  # create consumer service
  consumer:
    # configure build properties
    build: 
      # set build context to consumer devcontainer
      context: ./.devcontainer/consumer
      # limit build to development stage
      target: development
    # bind host to container to persist file changes
    volumes:
      - .:/workspace:cached
    # add service to network
    networks:
      - PingPong
    # enable allocation of terminal to container
    tty: true
    # keep standard input open on container
    stdin_open: true
    # overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

# create network
networks:
  # name network
  PingPong:
    # configure network type
    driver: bridge